### PR TITLE
Issue 10

### PR DESCRIPTION
**Pull request by peteryeeh**
What I did in issue 10

1. Delete getCurrent Function written by my own and get the timestamp variable from the exchange API object in the priceGetter file. It's better that we use exchange server time as our last update time rather than the time in our server. What's more, we have to use get current time library provided by others if we really need the function.

2. Group function loadMarketPrice and loadMarkPricebySymbol to one file and we can maintain the load market price feature easily. the same as 
 
3. Change for loop to for each while dealing with ordersArr. It reduces lots of redundant code.

4. About JS naming conventions. I am removing the s after the non-array variable and using the meaningful name to name the field of SQL header. For example, change status2 to unfilled status.

5. Add array filter to ordersGetter file for handling the undefined return from exchange API. 

6. Like point 2, I also group all functions about load orders to loadOrders file.

### CODE REVIEW

**Comment by peteryeeh** [comment]
I add the timestamp variable to the loadOrders function and then we can save the last update time for every symbol. When our system is ready to load the new orders users created from the exchange, we will load the data from the last update timestamp and we can avoid double load the same data.

In the next commit, I will deal with initializing past orders if the system reopened.

**Comment by peteryeeh** [comment]
I also inactive the isNewBar function. isNewBar is useful when we need to run the strategy. We don't need it now. Prices and orders can be synced at any time.

**Comment by guanjhensu** [comment]
It seems that you haven't validated data after the system talks to ccxt library / Binance API. I saw you use the array filter to get rid of the undefined data. However, the better way is to write the module to handle the unexcepted data. There are some libraries you can use: JOI or zod.

Moreover,  you removed the loadPastorder/loadNewOrder function, and only use the loadOrder function to get past orders. I notice that you save the orders' last update time to the object in the config file. It will result in a problem if the server shut down and your object value will be released. Then the system will lose the last update time. Maybe you have to write a function, pulling the last update time from the DB before the system's first-time load orders.

**Comment by peteryeeh** [comment]
I have opened the new issue to solve this problem #12  #14

**Pull request merged**
